version: "3"

services:
  firefox:
    image: selenium/standalone-firefox-debug:3.14.0-curium

    ports:
      - "4444:4444"
      - "5900:5900"

    volumes:
      - "/dev/shm:/dev/shm"

    networks:
      - selenium

  web_app:
    dns:
      - 8.8.8.8
    build: .
    command: python -m web_app

    expose:
      - 8080

    environment:
      - SELENIUM=http://firefox:4444/wd/hub

    networks:
      - selenium
    depends_on:
      - firefox

volumes:
  devshm:

networks:
  selenium: